### ISSUE TITLE
possible typo on CoW Deep Dive Part 1

### ISSUE THREAD

**Issue by Analect** [phofl/phofl.github.io#9]
I was reading through your [cow deep-dive](https://phofl.github.io/cow-deep-dive.html) series. Thanks for putting that together.

At the beginning of Part 1, I was a little confused with:
"CoW will disallow this behavior and ensures that only `df` is updated."

Should that read:
"CoW will disallow this behavior and ensures that only `grades` is updated."

**Comment by phofl** [comment]
Thx you are completely correct, is fixed now.
